jobs:
  - job: BuildLinux
    displayName: Linux Build
    pool: 
      vmImage: ubuntu-16.04
    steps:
      - script: | 
          apt-get install llvm
        displayName: Install Deps
      - script: | 
          make release
        displayName: Build
      - script: |
          ./odin check examples/demo/demo.odin -vet
          ./odin run examples/demo/demo.odin
        displayName: Test
        
  - job: BuildMac
    displayName: Linux macOS
    pool: 
      vmImage: macOS-10.14
    steps:
      - script: | 
          brew install --with-toolchain llvm
        displayName: Install Deps
      - script: | 
          export PATH="/usr/local/opt/llvm/bin:$PATH" 
          make release
        displayName: Build
      - script: | 
          ./odin check examples/demo/demo.odin -vet
          ./odin run examples/demo/demo.odin
        displayName: Test