jobs:
  - job: BuildLinux
    displayName: Linux Build
    pool: 
      vmImage: ubuntu-16.04
    steps:
      - script: | 
          sudo apt-get -y install llvm
        displayName: Install Deps
      - script: | 
          make release
        displayName: Build
      - script: |
          ./odin check examples/demo/demo.odin -vet
          ./odin run examples/demo/demo.odin
        displayName: Test
        
  - job: BuildMac
    displayName: Linux macOS
    pool: 
      vmImage: macOS-10.13
    steps:
      - script: | 
          brew install llvm
        displayName: Install Deps
      - script: | 
          export PATH="/usr/local/opt/llvm/bin:$PATH"
          export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
          export CPPFLAGS="-I/usr/local/opt/llvm/include"
          make release
        displayName: Build
      - script: | 
          ./odin check examples/demo/demo.odin -vet
          ./odin run examples/demo/demo.odin
        displayName: Test